### PR TITLE
(tech) auto create gh-pages on CI build

### PR DESCRIPTION
**Pull request by Nate-Wilkins**
Use a fork of [travis-sphinx](https://github.com/Nate-Wilkins/travis-sphinx) to push built docs to a [gh-pages](https://pages.github.com/) branch on a successful `master` CI build.

### CODE REVIEW

**Comment by Nate-Wilkins** [comment]
Travis is lying right now. The build succeeded but the `gh-pages` branch wasn't updated with the latest docs. @runphilrun you'll have to follow the directions on travis-sphinx's repository README.md which will  tell you how to setup a `GH_TOKEN` to generate the docs.

**Comment by runphilrun** [comment]
@Nate-Wilkins I generated the token, can you test it out before I merge?

**Comment by Nate-Wilkins** [comment]
Sure thing. I'll push up another commit in a bit to kick off another CI build.

**Comment by Nate-Wilkins** [comment]
@runphilrun says it's still missing :scream: 

Did you add it to travis? (ie `GH_TOKEN`: xxx)

**Comment by runphilrun** [comment]
travis has environment variable `GH_TOKEN` and its value is a token I created to have access to public repos. Did I miss a step?

**Pull request merged**
